name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Build Application
        run: |
          make all
          cp -R build/*.app ${{ github.workspace }}
          chmod 755 ${{ github.workspace }}/*.app/Contents/MacOS/LinkLock

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: LinkLock ${{ github.sha }}
          path: |
            build/*.app