name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Build Application
        run: |
          make all
          cp -Rv build/*.app ${{ github.workspace }}/LinkLock.app && sudo chmod -Rvvv 755 ${{ github.workspace }}/LinkLock.app && sudo chmod -Rvvv 755 ${{ github.workspace }}/LinkLock.app/Contents && sudo chmod -Rvvv 755 ${{ github.workspace }}/LinkLock.app/Contents/Info.plist && sudo chmod -Rvvv 755 ${{ github.workspace }}/LinkLock.app/Contents/MacOS && sudo chmod -Rvvv 755 ${{ github.workspace }}/LinkLock.app/Contents/MacOS/LinkLock

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: LinkLock_${{ github.sha }}
          path: |
          ${{ github.workspace }}/LinkLock.app